'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module EnumDisplayStrings
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Rstyx.Utilities.EnumDisplayStrings", GetType(EnumDisplayStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kreis ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_Circle() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_Circle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kreisbogen ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_CircularArc() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_CircularArc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ellipse ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_Ellipse() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_Ellipse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die elliptischer Bogen ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_EllipticalArc() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_EllipticalArc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_General() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_General", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die hyperbolischer Bogen ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_HyperbolicArc() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_HyperbolicArc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Linie ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_Line() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die parabolischer Bogen ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_ParabolicArc() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdBsplineCurveType_ParabolicArc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grafik ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdCellType_Graphic() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdCellType_Graphic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Menü ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdCellType_Menu() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdCellType_Menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punkt ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdCellType_Point() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdCellType_Point", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktuell ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_Current() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_Current", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DWG ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_DWG() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_DWG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DXF ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_DXF() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_DXF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_Unknown() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DGN/V7 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_V7() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_V7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DGN/V8 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_V8() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdDesignFileFormat_V8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bogen ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Arc() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Arc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die B-Spline-Grenze ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_BsplineBoundary() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_BsplineBoundary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die B-Spline-Kurve ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_BsplineCurve() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_BsplineCurve", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die B-Spline-Knoten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_BsplineKnot() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_BsplineKnot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die B-Spline-Stützpunkt ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_BsplinePole() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_BsplinePole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die B-Spline-Oberfläche ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_BsplineSurface() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_BsplineSurface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die B-Spline-Dicke ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_BsplineWeight() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_BsplineWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zelle ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_CellHeader() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_CellHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bibliotheks-Zelle ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_CellLibraryHeader() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_CellLibraryHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Komlexe Polygonfläche ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_ComplexShape() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_ComplexShape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Komplexe Kette ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_ComplexString() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_ComplexString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kegel ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Cone() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Cone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Conic ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Conic() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Conic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kurve ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Curve() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Curve", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DesignFileHeader ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_DesignFileHeader() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_DesignFileHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DGN-Speicherkomponente ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_DgnStoreComponent() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_DgnStoreComponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DGN-Speicher ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_DgnStoreHeader() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_DgnStoreHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DigiSatzDaten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_DigSetData() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_DigSetData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bemaßung ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Dimension() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Dimension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ellipse ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Ellipse() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Ellipse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gruppendaten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_GroupData() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_GroupData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ebenenmaske ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_LevelMask() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_LevelMask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ebenensymbolik ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_LevelSymbology() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_LevelSymbology", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Linie ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Line() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Polygon ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_LineString() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_LineString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Matrix-Double-Daten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_MatrixDoubleData() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_MatrixDoubleData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Matrix ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_MatrixHeader() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_MatrixHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Matrix-Integer-Daten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_MatrixIntegerData() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_MatrixIntegerData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gitter ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_MeshHeader() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_MeshHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MicroStation ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_MicroStation() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_MicroStation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mehrfach-Linie ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_MultiLine() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_MultiLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die BenannteGruppen-Komponente ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_NamedGroupComponent() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_NamedGroupComponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die BenannteGruppe ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_NamedGroupHeader() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_NamedGroupHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punktkette ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_PointString() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_PointString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Raster-Komponente ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_RasterComponent() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_RasterComponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Raster-Rahmen ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_RasterFrame() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_RasterFrame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Raster ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_RasterHeader() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_RasterHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Raster-Referenz ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_RasterReference() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_RasterReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Raster-Referenz-Komponente ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_RasterReferenceComponent() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_RasterReferenceComponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Referenz-Anhang ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_ReferenceAttachment() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_ReferenceAttachment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reference-Überschreibung ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_ReferenceOverride() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_ReferenceOverride", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Polygonfläche ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Shape() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Shape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pseudozelle ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_SharedCell() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_SharedCell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pseudozellen-Definition ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_SharedCellDefinition() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_SharedCellDefinition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Solid ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Solid() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Solid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Oberfläche ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Surface() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Surface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tabelle ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Table() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Table", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tabellen-Eintrag ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_TableEntry() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_TableEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sachdaten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Tag() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Tag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_Text() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die TextKnoten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_TextNode() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_TextNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_View() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansichtsgruppe ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdElementType_ViewGroup() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdElementType_ViewGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MicroStation ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdFontType_MicroStation() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdFontType_MicroStation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die AutoCAD SHX ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdFontType_SHX() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdFontType_SHX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdFontType_Unknown() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdFontType_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Windows TrueType ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdFontType_WindowsTrueType() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdFontType_WindowsTrueType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die englisch ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdMeasurementSystem_English() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdMeasurementSystem_English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die metrisch ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdMeasurementSystem_Metric() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdMeasurementSystem_Metric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbestimmt ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdMeasurementSystem_Undefined() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdMeasurementSystem_Undefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standard ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdModelType_Default() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdModelType_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichnung ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdModelType_Drawing() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdModelType_Drawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Plan ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdModelType_Extraction() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdModelType_Extraction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdModelType_Normal() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdModelType_Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blatt ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdModelType_Sheet() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdModelType_Sheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Binär ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTagType_Binary() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTagType_Binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichenfolge ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTagType_Character() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTagType_Character", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gleitkomma ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTagType_Double() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTagType_Double", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lange Ganzzahl ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTagType_LongInteger() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTagType_LongInteger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kurze Ganzzahl ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTagType_ShortInteger() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTagType_ShortInteger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mitte Unten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_CenterBottom() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_CenterBottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mitte Mitte ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_CenterCenter() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_CenterCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mitte Oben ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_CenterTop() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_CenterTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Links Unten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_LeftBottom() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_LeftBottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Links Mitte ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_LeftCenter() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_LeftCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Links Oben ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_LeftTop() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_LeftTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rechts Unten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_RightBottom() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_RightBottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rechts Mitte ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_RightCenter() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_RightCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rechts Oben ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdTextJustification_RightTop() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdTextJustification_RightTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle Ansichten ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_All() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Ansicht ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_None() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht 1 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_View1() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_View1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht 2 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_View2() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_View2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht 3 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_View3() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_View3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht 4 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_View4() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_View4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht 5 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_View5() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_View5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht 6 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_View6() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_View6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht 7 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_View7() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_View7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht 8 ähnelt.
        '''</summary>
        Friend ReadOnly Property Bentley_Interop_MicroStationDGN_MsdViews_View8() As String
            Get
                Return ResourceManager.GetString("Bentley_Interop_MicroStationDGN_MsdViews_View8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Crimson Editor ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Apps_AppUtils_SupportedEditors_CrimsonEditor() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Apps_AppUtils_SupportedEditors_CrimsonEditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die jEdit ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Apps_AppUtils_SupportedEditors_jEdit() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Apps_AppUtils_SupportedEditors_jEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die kein Editor ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Apps_AppUtils_SupportedEditors_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Apps_AppUtils_SupportedEditors_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die UltraEdit ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Apps_AppUtils_SupportedEditors_UltraEdit() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Apps_AppUtils_SupportedEditors_UltraEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alfanumerisch ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_ArrayUtils_SortType_Alphanumeric() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_ArrayUtils_SortType_Alphanumeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Numerisch ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_ArrayUtils_SortType_Numeric() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_ArrayUtils_SortType_Numeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grenzlinie ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinition_MinimumClearance() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinition_MinimumClearance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die keine ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinition_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinition_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die aus Grafik ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinitionBase_CAD() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinitionBase_CAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die berechnet mit Bezugslinie G2 ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinitionBase_G2() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinitionBase_G2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nicht definiert ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinitionBase_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceDefinitionBase_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die benutzerdefiniert ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_Custom() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_Custom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ohne ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OLA 15 kV ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_OHL_15kV() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_OHL_15kV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OLA 1 kV ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_OHL_1kV() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_OHL_1kV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OLA 25 kV ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_OHL_25kV() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_OHL_25kV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OLA 3 kV ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_OHL_3kV() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceOptionalPart_OHL_3kV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deutsche Bahn ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceRulesScope_DBAG() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceRulesScope_DBAG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die keiner ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_ClearanceGauge_ClearanceRulesScope_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_ClearanceGauge_ClearanceRulesScope_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Werte im gedrehten Gleissystem erforderlich ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointConstraints_KnownCantedRailsSystem() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointConstraints_KnownCantedRailsSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Höhe erforderlich ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointConstraints_KnownHeight() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointConstraints_KnownHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lagekoordinaten erforderlich ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointConstraints_KnownPosition() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointConstraints_KnownPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die keine ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointConstraints_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointConstraints_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die eindeutige ID erforderlich ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointConstraints_UniqueID() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointConstraints_UniqueID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die eindeutige ID je Block erforderlich ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointConstraints_UniqueIDPerBlock() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointConstraints_UniqueIDPerBlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die keine ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointEditOptions_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointEditOptions_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Text als iGeo &quot;iTrassen-Codierung&quot; auswerten ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointEditOptions_Parse_iTC() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointEditOptions_Parse_iTC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gleis-Überhöhung aus Info ableiten ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointEditOptions_ParseInfoForActualCant() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointEditOptions_ParseInfoForActualCant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punktarten aus Info ableiten ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointEditOptions_ParseInfoForPointKind() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointEditOptions_ParseInfoForPointKind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Festpunkt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_FixPoint() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_FixPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Festpkt 1D ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_FixPoint1D() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_FixPoint1D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Festpkt 2D ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_FixPoint2D() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_FixPoint2D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Festpkt 3D ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_FixPoint3D() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_FixPoint3D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Messpkt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_MeasurePoint() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_MeasurePoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Messpkt 1 ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_MeasurePoint1() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_MeasurePoint1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Messpkt 2 ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_MeasurePoint2() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_MeasurePoint2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bahnsteig ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_Platform() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_Platform", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gleis ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_Rails() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_Rails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die GVP ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_RailsFixPoint() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_RailsFixPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schiene ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_RailTop() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_RailTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schiene 1 ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_RailTop1() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_RailTop1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schiene 2 ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointKind_RailTop2() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointKind_RailTop2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die iGeo &quot;iTrassen-Codierung&quot; erzeugen ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointOutputOptions_Create_iTC() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointOutputOptions_Create_iTC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ist-Überhöhung zur Info hinzufügen ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointOutputOptions_CreateInfoWithActualCant() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointOutputOptions_CreateInfoWithActualCant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punktart zur Info hinzufügen ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointOutputOptions_CreateInfoWithPointKind() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointOutputOptions_CreateInfoWithPointKind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die schlechte ID ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointStatusHints_BadID() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointStatusHints_BadID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die extreme Geometrie ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointStatusHints_ExtremeGeometry() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointStatusHints_ExtremeGeometry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die keine ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_GeoPointStatusHints_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_GeoPointStatusHints_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die eindeutig ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_KilometerStatus_Normal() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_KilometerStatus_Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ankommend ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_KilometerStatus_SkipIncoming() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_KilometerStatus_SkipIncoming", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die abgehend ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_KilometerStatus_SkipOutgoing() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_KilometerStatus_SkipOutgoing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_KilometerStatus_Unknown() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_KilometerStatus_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die einfach festgelegt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailFixing_Fixed() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailFixing_Fixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die nicht festgelegt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailFixing_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailFixing_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die stark festgelegt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailFixing_StrongFixed() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailFixing_StrongFixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die einfach festgelegt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailFixingRule_Fixed() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailFixingRule_Fixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die einfach festgelegt (nur am Bahnsteig) ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailFixingRule_FixedAtPlatform() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailFixingRule_FixedAtPlatform", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die nicht festgelegt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailFixingRule_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailFixingRule_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die stark festgelegt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailFixingRule_StrongFixed() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailFixingRule_StrongFixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ist ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailStatus_Actual() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailStatus_Actual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailStatus_Design() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailStatus_Design", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_RailStatus_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_RailStatus_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ausgabe A0 ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_A0() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_A0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ausgabe A1 ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_A1() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_A1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die D3 (7-Linien) ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_D3() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_D3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die THW (klassisch) ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_THW() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockFormat_THW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die iGeo ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockProgram_iGeo() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockProgram_iGeo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die iTrassePC ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockProgram_iTrassePC() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockProgram_iTrassePC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockProgram_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockProgram_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verm.esn ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockProgram_VermEsn() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockProgram_VermEsn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Variable Felder (CSV) ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockSubFormat_CSV() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockSubFormat_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockSubFormat_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockSubFormat_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die einzeilig ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockSubFormat_OneLine() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockSubFormat_OneLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die zweizeilig ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockSubFormat_TwoLine() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockSubFormat_TwoLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die aktuell ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockVersion_Current() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockVersion_Current", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbekannt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockVersion_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockVersion_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die veraltet ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcBlockVersion_Outdated() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcBlockVersion_Outdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Werte im Gleissystem erforderlich ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcConstraints_CantedRailsSystemRequired() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcConstraints_CantedRailsSystemRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die keine ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TcFileReader_TcConstraints_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TcFileReader_TcConstraints_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die beide ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TrackSide_Both() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TrackSide_Both", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die links ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TrackSide_Left() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TrackSide_Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die unbestimmt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TrackSide_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TrackSide_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die rechts ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Domain_TrackSide_Right() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Domain_TrackSide_Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kilometerschreibweise akzeptieren ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_AllowKilometerNotation() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_AllowKilometerNotation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Führende Sternchen (&quot;*&quot;) ignorieren ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_IgnoreLeadingAsterisks() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_IgnoreLeadingAsterisks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehlenden Wert als &quot;0&quot; ansehen ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_MissingAsZero() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_MissingAsZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die keine ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nicht numerischen Wert als Zahl 0.0 ansehen ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_NonNumericAsNaN() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_NonNumericAsNaN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feld ist nicht erforderlich ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_NotRequired() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_NotRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichenkette trimmen ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_Trim() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_Trim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichenkette am Ende trimmen ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_TrimEnd() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_TrimEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zahl 0.0 als nicht definiert ansehen ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldOptions_ZeroAsNaN() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldOptions_ZeroAsNaN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Spalte und Länge ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldPositionType_ColumnAndLength() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldPositionType_ColumnAndLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feld wird ignoriert ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldPositionType_Ignore() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldPositionType_Ignore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wortnummer ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldPositionType_WordNumber() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldPositionType_WordNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wortnummer und Rest der Zeile ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_DataFieldPositionType_WordNumberAndRemains() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_DataFieldPositionType_WordNumberAndRemains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Basisname ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Base() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Basis.Erweiterung ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Base_Ext() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Base_Ext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Klasse ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Class() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Class", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verzeichnis ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Dir() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Dir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verzeichnis\Basis ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Dir_Base() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Dir_Base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verzeichnis\Basis.Erweiterung ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Dir_Base_Ext() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Dir_Base_Ext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verzeichnis\Projekt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Dir_Proj() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Dir_Proj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Laufwerk ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Drive() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Drive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erweiterung ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Ext() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Ext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Projekt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_FileUtils_FilePart_Proj() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_FileUtils_FilePart_Proj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_ParseErrorLevel_Error() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_ParseErrorLevel_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warnung ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_IO_ParseErrorLevel_Warning() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_IO_ParseErrorLevel_Warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hintergrund ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_UI_WarningColorMode_Background() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_UI_WarningColorMode_Background", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vordergrund ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_UI_WarningColorMode_Foreground() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_UI_WarningColorMode_Foreground", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die kein ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_UI_WarningColorMode_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_UI_WarningColorMode_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die fehlerhaft ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Validation_VerificationResult_Failure() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Validation_VerificationResult_Failure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die nicht geprüft ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Validation_VerificationResult_None() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Validation_VerificationResult_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die nicht prüfbar ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Validation_VerificationResult_NotVerifiable() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Validation_VerificationResult_NotVerifiable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die bestätigt ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Validation_VerificationResult_Success() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Validation_VerificationResult_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die evtl. fehlerhaft ähnelt.
        '''</summary>
        Friend ReadOnly Property Rstyx_Utilities_Validation_VerificationResult_Warning() As String
            Get
                Return ResourceManager.GetString("Rstyx_Utilities_Validation_VerificationResult_Warning", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
