'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34014
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Rstyx.Utilities.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Editor &apos;%s&apos; ist nicht verfügbar. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppUtils_EditorNotAvailable() As String
            Get
                Return ResourceManager.GetString("AppUtils_EditorNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler beim Start des Excel-GeoTools-Import der Datei &apos;%s&apos; ... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppUtils_ErrorInvokingXlGeoToolsImport() As String
            Get
                Return ResourceManager.GetString("AppUtils_ErrorInvokingXlGeoToolsImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CSV-Datei für Excel-GeoTools-Import nicht gefunden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppUtils_GeoToolsCsvNotFound() As String
            Get
                Return ResourceManager.GetString("AppUtils_GeoToolsCsvNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;%s&apos; ist kein gültiger Editor. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppUtils_InvalidEditor() As String
            Get
                Return ResourceManager.GetString("AppUtils_InvalidEditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte Excel-GeoTools-CSV-Import der Datei &apos;%s&apos; ... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppUtils_InvokeGeoToolsCsvImport() As String
            Get
                Return ResourceManager.GetString("AppUtils_InvokeGeoToolsCsvImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es ist kein Editor verfügbar. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppUtils_NoEditorAvailable() As String
            Get
                Return ResourceManager.GetString("AppUtils_NoEditorAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der angeforderte Editor &apos;%s&apos; wird nicht unterstützt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppUtils_NotSupportedEditor() As String
            Get
                Return ResourceManager.GetString("AppUtils_NotSupportedEditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Import nach Excel nicht möglich, da extrahiertes VB-Skript nicht existiert. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AppUtils_XlmVBScriptNotFound() As String
            Get
                Return ResourceManager.GetString("AppUtils_XlmVBScriptNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unerwarteter Fehler bei asynchroner Ausführung des Befehls &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AsyncDelegateUICommand_AsyncExecuteFailed() As String
            Get
                Return ResourceManager.GetString("AsyncDelegateUICommand_AsyncExecuteFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler beim Abbruch des Task. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AsyncDelegateUICommand_ErrorCancellingTask() As String
            Get
                Return ResourceManager.GetString("AsyncDelegateUICommand_ErrorCancellingTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erzeugen des Abbruch-Befehls. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AsyncDelegateUICommand_ErrorCreatingCancelCommand() As String
            Get
                Return ResourceManager.GetString("AsyncDelegateUICommand_ErrorCreatingCancelCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler bei Aufruf der Ereignis-Handler für Befehl &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AsyncDelegateUICommand_ErrorInCalledCanExecuteChangedHandler() As String
            Get
                Return ResourceManager.GetString("AsyncDelegateUICommand_ErrorInCalledCanExecuteChangedHandler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unerwarteter Fehler bei synchroner Ausführung des Befehls &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AsyncDelegateUICommand_SyncExecuteFailed() As String
            Get
                Return ResourceManager.GetString("AsyncDelegateUICommand_SyncExecuteFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler bei Anschlussbearbeitung nach Ausführung des Befehls &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AsyncDelegateUICommand_TaskFinishingFailed() As String
            Get
                Return ResourceManager.GetString("AsyncDelegateUICommand_TaskFinishingFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die %s, Zeilen %d bis %d. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataBlockFileSourceInfo_ToString() As String
            Get
                Return ResourceManager.GetString("DataBlockFileSourceInfo_ToString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeile %d enthält keine Daten. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_EmptyDataLine() As String
            Get
                Return ResourceManager.GetString("DataTextLine_EmptyDataLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Feld &apos;%s&apos; enthält keinen gültigen Wert (%s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_InvalidFieldNotEnumMember() As String
            Get
                Return ResourceManager.GetString("DataTextLine_InvalidFieldNotEnumMember", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Feld &apos;%s&apos; stellt keine ganze Zahl zwischen %d und %d dar (%s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_InvalidFieldNotInteger() As String
            Get
                Return ResourceManager.GetString("DataTextLine_InvalidFieldNotInteger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Feld &apos;%s&apos; ist keine gültige Kilometer-Angabe (%s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_InvalidFieldNotKilometer() As String
            Get
                Return ResourceManager.GetString("DataTextLine_InvalidFieldNotKilometer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Feld &apos;%s&apos; stellt keine ganze Zahl zwischen %d und %d dar (%s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_InvalidFieldNotLong() As String
            Get
                Return ResourceManager.GetString("DataTextLine_InvalidFieldNotLong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Feld &apos;%s&apos; ist nicht numerisch (%s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_InvalidFieldNotNumeric() As String
            Get
                Return ResourceManager.GetString("DataTextLine_InvalidFieldNotNumeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Feld &apos;%s&apos; existiert nicht (Spalte %d, Länge %d). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_MissingField() As String
            Get
                Return ResourceManager.GetString("DataTextLine_MissingField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Feld &apos;%s&apos; existiert nicht (%d. Feld). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_MissingWord() As String
            Get
                Return ResourceManager.GetString("DataTextLine_MissingWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gültige Werte sind:  %s. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataTextLine_ValidValues() As String
            Get
                Return ResourceManager.GetString("DataTextLine_ValidValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datenbank-Verbindung zur Excel-Arbeitsmappe &apos;%s&apos; konnte nicht hergestelt werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DBUtils_ConnectionToExcelWorkbookFailed() As String
            Get
                Return ResourceManager.GetString("DBUtils_ConnectionToExcelWorkbookFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Excel-Arbeitsmappe nicht gefunden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DBUtils_ExcelWorkbookNotFound() As String
            Get
                Return ResourceManager.GetString("DBUtils_ExcelWorkbookNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Feld &apos;%s&apos; existiert nicht in der Tabelle &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DBUtils_FieldNotFoundInTable() As String
            Get
                Return ResourceManager.GetString("DBUtils_FieldNotFoundInTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tabelle &apos;%s&apos; aus Excel-Arbeitsmappe &apos;%s&apos; konnte nicht geöffnet werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DBUtils_OpenExcelWorksheetFailed() As String
            Get
                Return ResourceManager.GetString("DBUtils_OpenExcelWorksheetFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kommentar ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Com() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Com", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kommentar 2 ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Com2() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Com2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kommentar ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Comment() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Comment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Steigungswinkel ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_G() As String
            Get
                Return ResourceManager.GetString("Domain_Label_G", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Höhe über der Gradiente ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_H() As String
            Get
                Return ResourceManager.GetString("Domain_Label_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Höhe über DGM ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_HDGM() As String
            Get
                Return ResourceManager.GetString("Domain_Label_HDGM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anhebung der unteren Schiene zur Gradiente ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Heb() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Heb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Höhe über SOK im gedrehten Gleissystem ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_HG() As String
            Get
                Return ResourceManager.GetString("Domain_Label_HG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hoch im Strassensystem ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_HGS() As String
            Get
                Return ResourceManager.GetString("Domain_Label_HGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hoch im Tunnelsystem ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_HGT() As String
            Get
                Return ResourceManager.GetString("Domain_Label_HGT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Höhe über SOK ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_HSOK() As String
            Get
                Return ResourceManager.GetString("Domain_Label_HSOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kilometer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Km() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Km", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status des Kilometers ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_KmStatus() As String
            Get
                Return ResourceManager.GetString("Domain_Label_KmStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abwicklungsmass (Tunnelprofil) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_L() As String
            Get
                Return ResourceManager.GetString("Domain_Label_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abwicklungsmass (Gleisprofil) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_LG() As String
            Get
                Return ResourceManager.GetString("Domain_Label_LG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punkt-ID ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_PointID() As String
            Get
                Return ResourceManager.GetString("Domain_Label_PointID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abstand zur Achse ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Q() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Q", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Querabstand im gedrehten Gleissystem ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_QG() As String
            Get
                Return ResourceManager.GetString("Domain_Label_QG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quer im Strassensystem ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_QGS() As String
            Get
                Return ResourceManager.GetString("Domain_Label_QGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quer im Tunnelsystem ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_QGT() As String
            Get
                Return ResourceManager.GetString("Domain_Label_QGT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abstand zur Km-Linie ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_QKm() As String
            Get
                Return ResourceManager.GetString("Domain_Label_QKm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abstand zur Achse in Tunnelvortriebsrichtung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_QT() As String
            Get
                Return ResourceManager.GetString("Domain_Label_QT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Radialer Abstand zum Tunnelprofil ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_R() As String
            Get
                Return ResourceManager.GetString("Domain_Label_R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Radius ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Ra() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Ra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Radialer Abstand zum Gleisprofil ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_RG() As String
            Get
                Return ResourceManager.GetString("Domain_Label_RG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Richtung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Ri() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Ri", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Station ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_St() As String
            Get
                Return ResourceManager.GetString("Domain_Label_St", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punktinformation ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Text() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tunnelmeter ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Tm() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Tm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Überhöhung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Ueb() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Ueb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Überhöhung linke Schiene ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_UebL() As String
            Get
                Return ResourceManager.GetString("Domain_Label_UebL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Überhöhung reche  Schiene ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_UebR() As String
            Get
                Return ResourceManager.GetString("Domain_Label_UebR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Höhe über Strassenprofil ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_V() As String
            Get
                Return ResourceManager.GetString("Domain_Label_V", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die X (Hochwert) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_X() As String
            Get
                Return ResourceManager.GetString("Domain_Label_X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Y (Rechtswert) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Y() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Y", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punkthöhe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_Z() As String
            Get
                Return ResourceManager.GetString("Domain_Label_Z", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die DGM-Modellhöhe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_ZDGM() As String
            Get
                Return ResourceManager.GetString("Domain_Label_ZDGM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Höhe der Gradiente ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_ZLGS() As String
            Get
                Return ResourceManager.GetString("Domain_Label_ZLGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SOK-Höhe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Domain_Label_ZSOK() As String
            Get
                Return ResourceManager.GetString("Domain_Label_ZSOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Zieltyp &apos;%s&apos; ist kein System.Enum. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property EnumUtils_InvalidTargetType() As String
            Get
                Return ResourceManager.GetString("EnumUtils_InvalidTargetType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler bei Verarbeitung der Dateien des Ordners &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_ErrorProcessingFolder() As String
            Get
                Return ResourceManager.GetString("FileUtils_ErrorProcessingFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler bei Verarbeitung der Unterverzeichnisse des Ordners &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_ErrorProcessingSubFolders() As String
            Get
                Return ResourceManager.GetString("FileUtils_ErrorProcessingSubFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungültiger Dateiname konnte nicht bereinigt werden: &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_ErrorValidatingInvalidFileName() As String
            Get
                Return ResourceManager.GetString("FileUtils_ErrorValidatingInvalidFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungültiger Dateipfad konnte nicht bereinigt werden: &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_ErrorValidatingInvalidFilePath() As String
            Get
                Return ResourceManager.GetString("FileUtils_ErrorValidatingInvalidFilePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aufgerufen mit nicht unterstütztem FilePart-Enum-Wert: &apos;%s&apos; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_InvalidFilepartEnumValue() As String
            Get
                Return ResourceManager.GetString("FileUtils_InvalidFilepartEnumValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein existierendes Verzeichnis angegeben. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_NoExistentFolderName() As String
            Get
                Return ResourceManager.GetString("FileUtils_NoExistentFolderName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Dateimaske(n) angegeben. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_NoFileFilter() As String
            Get
                Return ResourceManager.GetString("FileUtils_NoFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine zu durchsuchenden Verzeichnisse angegeben. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_NoSearchDir() As String
            Get
                Return ResourceManager.GetString("FileUtils_NoSearchDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keinen gültigen Dateifilter angegeben. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_NoValidFileFilter() As String
            Get
                Return ResourceManager.GetString("FileUtils_NoValidFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateipfad ist zu lang: &apos;%s&apos; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_PathTooLong() As String
            Get
                Return ResourceManager.GetString("FileUtils_PathTooLong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verzeichnis für Dateisuche existiert nicht: &apos;%s&apos; (Arbeitsverzeichnis: &apos;%s&apos;). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_SearchFolderNotFound() As String
            Get
                Return ResourceManager.GetString("FileUtils_SearchFolderNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Leerer Dateifilter für Dateisuche wird ignoriert. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_SearchIgnoresEmptyFileFilter() As String
            Get
                Return ResourceManager.GetString("FileUtils_SearchIgnoresEmptyFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Leeres Verzeichnis für Dateisuche wird ignoriert. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_SearchIgnoresEmptyFolderName() As String
            Get
                Return ResourceManager.GetString("FileUtils_SearchIgnoresEmptyFolderName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateifilter für Dateisuche enthält ungültige Zeichen und wird ignoriert: &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_SearchIgnoresInvalidFileFilter() As String
            Get
                Return ResourceManager.GetString("FileUtils_SearchIgnoresInvalidFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verzeichnis für Dateisuche enthält ungültige Zeichen und wird ignoriert: &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_SearchIgnoresInvalidFolderName() As String
            Get
                Return ResourceManager.GetString("FileUtils_SearchIgnoresInvalidFolderName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateifilter für Dateisuche ist wiederholt angegeben und wird ignoriert: &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_SearchIgnoresRepeatedFileFilter() As String
            Get
                Return ResourceManager.GetString("FileUtils_SearchIgnoresRepeatedFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verzeichnis für Dateisuche ist wiederholt angegeben und wird ignoriert: &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FileUtils_SearchIgnoresRepeatedFolderName() As String
            Get
                Return ResourceManager.GetString("FileUtils_SearchIgnoresRepeatedFolderName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unerwarteter Anwendungsfehler (Application_DispatcherUnhandledException). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_DispatcherUnhandledException() As String
            Get
                Return ResourceManager.GetString("Global_DispatcherUnhandledException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler bei Ausführung von Cinch.ApplicationHelper.DoEvents(). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_DoEventsFailed() As String
            Get
                Return ResourceManager.GetString("Global_DoEventsFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erzeugen eines Befehls in %s(). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_ErrorCreatingCommandIn() As String
            Get
                Return ResourceManager.GetString("Global_ErrorCreatingCommandIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler in einem aufgerufenen Ereignishandler. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_ErrorFromCalledEventHandler() As String
            Get
                Return ResourceManager.GetString("Global_ErrorFromCalledEventHandler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Ereignisbehandlung. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_ErrorFromInsideEventHandler() As String
            Get
                Return ResourceManager.GetString("Global_ErrorFromInsideEventHandler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datei ist schreibgeschützt: &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_FileIsReadOnly() As String
            Get
                Return ResourceManager.GetString("Global_FileIsReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungültiges Typ-Argument (Typ &apos;%s&apos; wird nicht unterstützt) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_InvalidTypeArgument() As String
            Get
                Return ResourceManager.GetString("Global_InvalidTypeArgument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;%s()&apos; wurde noch nicht implementiert! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_NotImplemented() As String
            Get
                Return ResourceManager.GetString("Global_NotImplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateiliste ist leer =&gt; Nichts zu tun. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_NoWork_EmptyFileList() As String
            Get
                Return ResourceManager.GetString("Global_NoWork_EmptyFileList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Elemente gefunden =&gt; Nichts zu tun. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_NoWork_NoElementsFound() As String
            Get
                Return ResourceManager.GetString("Global_NoWork_NoElementsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eigenschaft &apos;%s&apos; ist schreibgeschützt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_PropertyIsReadOnly() As String
            Get
                Return ResourceManager.GetString("Global_PropertyIsReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eigenschaft &apos;%s&apos; existiert nicht. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_PropertyNotFound() As String
            Get
                Return ResourceManager.GetString("Global_PropertyNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Resource konnte nicht gelesen werden: &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_ResourceNotFound() As String
            Get
                Return ResourceManager.GetString("Global_ResourceNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unerwarteter Fehler. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_UnexpectedError() As String
            Get
                Return ResourceManager.GetString("Global_UnexpectedError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unerwarteter Fehler in %s(). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_UnexpectedErrorIn() As String
            Get
                Return ResourceManager.GetString("Global_UnexpectedErrorIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Wert muss größer als Null sein. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Global_ValueNotGreaterThanZero() As String
            Get
                Return ResourceManager.GetString("Global_ValueNotGreaterThanZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Zeichenkette &apos;%s&apos; stellt keine gültige Kilomerschreibweise dar. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Kilometer_InvalidKilometerNotation() As String
            Get
                Return ResourceManager.GetString("Kilometer_InvalidKilometerNotation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die %s in Zeile %d: %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ParseError_ErrorLevelInLineNo() As String
            Get
                Return ResourceManager.GetString("ParseError_ErrorLevelInLineNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Km ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PositionAtTrack_Label_Kilometer() As String
            Get
                Return ResourceManager.GetString("PositionAtTrack_Label_Kilometer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kode/RiKz ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PositionAtTrack_Label_RailsCode() As String
            Get
                Return ResourceManager.GetString("PositionAtTrack_Label_RailsCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gleis ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PositionAtTrack_Label_RailsName() As String
            Get
                Return ResourceManager.GetString("PositionAtTrack_Label_RailsName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Seite ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PositionAtTrack_Label_Side() As String
            Get
                Return ResourceManager.GetString("PositionAtTrack_Label_Side", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Strecke ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PositionAtTrack_Label_Track() As String
            Get
                Return ResourceManager.GetString("PositionAtTrack_Label_Track", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Streckenposition unbekannt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PositionAtTrack_Label_UnKnownPosition() As String
            Get
                Return ResourceManager.GetString("PositionAtTrack_Label_UnKnownPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Basis für Überhöhung ist ungültig (negativ) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RailPair_InvalidCantBaseNegative() As String
            Get
                Return ResourceManager.GetString("RailPair_InvalidCantBaseNegative", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gleis: Überhöhung = %.2f mm, Basis für Überhöhung = %.3f m ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RailPair_ToString() As String
            Get
                Return ResourceManager.GetString("RailPair_ToString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Überhöhung ist unbekannt (NaN) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RailPair_UnknownCant() As String
            Get
                Return ResourceManager.GetString("RailPair_UnknownCant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Basis für Überhöhung ist unbekannt (NaN) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RailPair_UnknownCantBase() As String
            Get
                Return ResourceManager.GetString("RailPair_UnknownCantBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gleiskonfiguration ist unbekannt (Überhöhung, Basis für Überhöhung). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RailPair_UnknownConfiguration() As String
            Get
                Return ResourceManager.GetString("RailPair_UnknownConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nicht erkannte Escape Sequenz: \{0} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Sprintf_InvalidEscapeSequence() As String
            Get
                Return ResourceManager.GetString("Sprintf_InvalidEscapeSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nicht erkannte Parameter Sequenz: %{0}{1}{2}{3} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Sprintf_InvalidParameterSequence() As String
            Get
                Return ResourceManager.GetString("Sprintf_InvalidParameterSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die sprintf(): unerwarteter Fehler (FormatString = &apos;{0}&apos;) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Sprintf_UnexpectedError() As String
            Get
                Return ResourceManager.GetString("Sprintf_UnexpectedError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blocktyp ist ungültig (evtl. nicht vollständig bekannt). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_InvalidBlockType_Fallback() As String
            Get
                Return ResourceManager.GetString("TcBlock_InvalidBlockType_Fallback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Trassenbezug ist ungültig (zu wenig bekannte Werte). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_InvalidTrackRef_Fallback() As String
            Get
                Return ResourceManager.GetString("TcBlock_InvalidTrackRef_Fallback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  lfd              PunktNr  Kilometer    Station     Quer     HSOK        QG       HG       RG       Radius Usoll  U_ist  SO-Höhe   Info              Rechtswert     Hochwert    Hoehe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_TableHeader() As String
            Get
                Return ResourceManager.GetString("TcBlock_TableHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beschreibung:  %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_ToReport_Comment() As String
            Get
                Return ResourceManager.GetString("TcBlock_ToReport_Comment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punkte:        %d ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_ToReport_Points() As String
            Get
                Return ResourceManager.GetString("TcBlock_ToReport_Points", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quelle:        %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_ToReport_Source() As String
            Get
                Return ResourceManager.GetString("TcBlock_ToReport_Source", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Trassenbezug:  %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_ToReport_TrackRef() As String
            Get
                Return ResourceManager.GetString("TcBlock_ToReport_TrackRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ:           %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_ToReport_Type() As String
            Get
                Return ResourceManager.GetString("TcBlock_ToReport_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die %s [%d Punkte, %s] ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlock_ToString() As String
            Get
                Return ResourceManager.GetString("TcBlock_ToString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Block-Format &apos;%s&apos; passt nicht zum Herkunfts-Programm &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlockType_FormatMismatch() As String
            Get
                Return ResourceManager.GetString("TcBlockType_FormatMismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feldnamen des CSV-Formats sind unbekannt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlockType_MissingFieldNames() As String
            Get
                Return ResourceManager.GetString("TcBlockType_MissingFieldNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Block-Format ist unbekannt (Unterstützte Formate für %s: %s und %s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlockType_MissingFormat() As String
            Get
                Return ResourceManager.GetString("TcBlockType_MissingFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Herkunfts-Programm ist unbekannt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlockType_MissingProgram() As String
            Get
                Return ResourceManager.GetString("TcBlockType_MissingProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Block-Unterformat (ein-/zweizeilig) ist unbekannt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlockType_MissingSubFormat() As String
            Get
                Return ResourceManager.GetString("TcBlockType_MissingSubFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Programmversion ist unbekannt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcBlockType_MissingVersion() As String
            Get
                Return ResourceManager.GetString("TcBlockType_MissingVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Werte im gedrehten Gleissystem können nicht bestimmt werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_Constraints_MissingCantedRailsSystem() As String
            Get
                Return ResourceManager.GetString("TcFileReader_Constraints_MissingCantedRailsSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Vorzeichen der Überhöhung kann nicht bestimmt werden, weil der Radius Null ist. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_Constraints_MissingCantSign() As String
            Get
                Return ResourceManager.GetString("TcFileReader_Constraints_MissingCantSign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Block mit Trassenkoordinaten enthält keine gültigen Punkte (Zeilen %d bis %d). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_EmptyTcBlock() As String
            Get
                Return ResourceManager.GetString("TcFileReader_EmptyTcBlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punkt-ID (%s) existiert bereits in diesem Block. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_IDdoubled() As String
            Get
                Return ResourceManager.GetString("TcFileReader_IDdoubled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zweite Zeile des Datensatzes enthält nicht die gleiche Punkt-ID wie die erste Zeile (%s statt %s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_IDMismatch() As String
            Get
                Return ResourceManager.GetString("TcFileReader_IDMismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungültiger Block mit Trassenkoordinaten (Zeilen %d bis %d):\n%s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_InvalidTcBlock() As String
            Get
                Return ResourceManager.GetString("TcFileReader_InvalidTcBlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die =&gt; Datei mit Trassenkoordinaten konnte nicht erfolgreich gelesen werden (%s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_LoadFailed() As String
            Get
                Return ResourceManager.GetString("TcFileReader_LoadFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zweite Zeile des Datensatzes fehlt (diese muss unmittelbar auf die erste Zeile folgen). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_MissingSecondLine() As String
            Get
                Return ResourceManager.GetString("TcFileReader_MissingSecondLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die =&gt; Datei mit Trassenkoordinaten enthält keine Punkte (%s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_NoPoints() As String
            Get
                Return ResourceManager.GetString("TcFileReader_NoPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es sind %d Fehler aufgetreten beim Analysieren der Trassenkoordinaten (%s). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_ParsingFailed() As String
            Get
                Return ResourceManager.GetString("TcFileReader_ParsingFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Block-Nr:      %d ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_ToReport_BlockNo() As String
            Get
                Return ResourceManager.GetString("TcFileReader_ToReport_BlockNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blöcke:  %d ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_ToReport_Blocks() As String
            Get
                Return ResourceManager.GetString("TcFileReader_ToReport_Blocks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler:  %d ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_ToReport_Errors() As String
            Get
                Return ResourceManager.GetString("TcFileReader_ToReport_Errors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datei:   %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_ToReport_File() As String
            Get
                Return ResourceManager.GetString("TcFileReader_ToReport_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Punkte:  %d ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_ToReport_Points() As String
            Get
                Return ResourceManager.GetString("TcFileReader_ToReport_Points", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die %s (%s Blöcke, %s Punkte, %s Fehler) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TcFileReader_ToString() As String
            Get
                Return ResourceManager.GetString("TcFileReader_ToString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Achsname und DGM-Name sind unbekannt (mindestens einer der beiden muss bekannt sein). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_MissingNameOfAlignmentOrDTM() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_MissingNameOfAlignmentOrDTM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Achse:           %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfAlignment() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfAlignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Überhöhung:      %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfCantLine() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfCantLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Geländemodell:   %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfDTM() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfDTM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gradiente:       %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfGradientLine() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfGradientLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Km-Linie:        %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfKmAlignment() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfKmAlignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gleisprofile:    %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfRaillSections() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfRaillSections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Straßenprofile:  %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfRoadSections() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfRoadSections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Profilpunkte:    %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfSectionPoints() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfSectionPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tunnelprofile:   %s ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackGeometryInfo_NameOfTunnelSections() As String
            Get
                Return ResourceManager.GetString("TrackGeometryInfo_NameOfTunnelSections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Strecke %d ähnelt.
        '''</summary>
        Public Shared ReadOnly Property TrackTitle_ToString() As String
            Get
                Return ResourceManager.GetString("TrackTitle_ToString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erstellen des Icon-DrawingBrush &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UIResources_ErrorCreatingIconDrawingBrush() As String
            Get
                Return ResourceManager.GetString("UIResources_ErrorCreatingIconDrawingBrush", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erstellen des Icon-Rechtecks &apos;%s&apos;. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property UIResources_ErrorCreatingIconRectangle() As String
            Get
                Return ResourceManager.GetString("UIResources_ErrorCreatingIconRectangle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
