'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace IO.CSV
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CsvExceptionMessage
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Rstyx.Utilities.CsvExceptionMessage", GetType(CsvExceptionMessage).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Buffer size must be 1 or more. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BufferSizeTooSmall() As String
            Get
                Return ResourceManager.GetString("BufferSizeTooSmall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cannot move to a previous record in forward-only mode. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CannotMovePreviousRecordInForwardOnly() As String
            Get
                Return ResourceManager.GetString("CannotMovePreviousRecordInForwardOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cannot read record at index &apos;{0}&apos;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CannotReadRecordAtIndex() As String
            Get
                Return ResourceManager.GetString("CannotReadRecordAtIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enumeration has either not started or has already finished. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EnumerationFinishedOrNotStarted() As String
            Get
                Return ResourceManager.GetString("EnumerationFinishedOrNotStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Collection was modified; enumeration operation may not execute. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EnumerationVersionCheckFailed() As String
            Get
                Return ResourceManager.GetString("EnumerationVersionCheckFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; field header not found. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FieldHeaderNotFound() As String
            Get
                Return ResourceManager.GetString("FieldHeaderNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Field index must be included in [0, FieldCount[. Specified field index was : &apos;{0}&apos;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FieldIndexOutOfRange() As String
            Get
                Return ResourceManager.GetString("FieldIndexOutOfRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The CSV appears to be corrupt near record &apos;{0}&apos; field &apos;{1} at position &apos;{2}&apos;. Current raw data : &apos;{3}&apos;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MalformedCsvException() As String
            Get
                Return ResourceManager.GetString("MalformedCsvException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not a supported missing field action. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MissingFieldActionNotSupported() As String
            Get
                Return ResourceManager.GetString("MissingFieldActionNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No current record. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoCurrentRecord() As String
            Get
                Return ResourceManager.GetString("NoCurrentRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The CSV does not have headers (CsvReader.HasHeaders property is false). ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoHeaders() As String
            Get
                Return ResourceManager.GetString("NoHeaders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The number of fields in the record is greater than the available space from index to the end of the destination array. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotEnoughSpaceInArray() As String
            Get
                Return ResourceManager.GetString("NotEnoughSpaceInArray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not a valid ParseErrorAction while inside a ParseError event. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ParseErrorActionInvalidInsideParseErrorEvent() As String
            Get
                Return ResourceManager.GetString("ParseErrorActionInvalidInsideParseErrorEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not a supported ParseErrorAction. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ParseErrorActionNotSupported() As String
            Get
                Return ResourceManager.GetString("ParseErrorActionNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This operation is invalid when the reader is closed. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReaderClosed() As String
            Get
                Return ResourceManager.GetString("ReaderClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Record index must be 0 or more. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RecordIndexLessThanZero() As String
            Get
                Return ResourceManager.GetString("RecordIndexLessThanZero", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
